### ISSUE TITLE
Questions regarding getUniqueId()

### ISSUE THREAD

**Issue by prox2** [react-native-device-info/react-native-device-info#1316] opened 2021-09-24 02:35 UTC
This is not a bug report, I have some question regarding the method getUniqueId().
Based on the documentation 
`iOS: This is IDFV or a random string if IDFV is unavaliable. Once UID is generated it is stored in iOS Keychain and NSUserDefaults. So it would stay the same even if you delete the app or reset IDFV. You can carefully consider it a persistent, cross-install unique ID. It can be changed only in case someone manually override values in Keychain/NSUserDefaults or if Apple would change Keychain and NSUserDefaults implementations. Beware: The IDFV is calculated using your bundle identifier and thus will be different in app extensions.
android: Prior to Oreo, this id (ANDROID_ID) will always be the same once you set up your phone.` 

 that this id only change when the user reset the phone to factory setting, however based on these questions https://github.com/react-native-device-info/react-native-device-info/issues/1193#issuecomment-815083492 https://github.com/react-native-device-info/react-native-device-info/issues/1183#issue-837115985 is shows that is changed on reinstall and that is no other way to get permanent  id.

I have tried to reinstall the app both for IOS and Android but the id is remain the same, but based on the mentioned questions they got different ids when reinstall the app.

My question is in which case exactly it changed expect factory reset?

Also in my case I am doing rewarding for new users who install the app for the first time, so Is it safe to validate them using this id? or is there any better approach?

**Comment by mikehardy** [comment] 2021-09-25 14:05
> I have tried to reinstall the app both for IOS and Android but the id is remain the same

I suspect the uninstall is not complete somehow? You should specify the exact steps, as most people reproduce the behavior on iOS at minimum where IDFV is a new value after complete uninstall (app delete) / fresh install. 

I don't think a strategy based on identifying hardware devices in the absence of some user account is very secure at all. For your use case I would consider it a classic security tradeoff: that is the cost of circumventing some protection needs to be higher than the reward, then the behavior you want to stop is self-limiting. Stated differently: If a new app install is smaller than what most users value their time at, you can still give a reward (which makes people feel nice) but you don't have to worry about reinstall abuse because it's not really worth it.

Pending exact steps including all versions of everything (software and hardware models tested) I'm going to close this as it is not the experience of any other reporters and I suspect will not be reproducible

**Closed by mikehardy** 2021-09-25 14:05 UTC
