### ISSUE TITLE
Exception in HostObject::get(propName:RNDeviceInfo): <unknown>

### ISSUE THREAD

**Issue by MAlexD** [react-native-device-info/react-native-device-info#1239] opened 2021-05-17 13:26 UTC
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.1.3   |
| Affected OS | iOS   |
| OS Version  | 14.5  |

## Current behavior

On startup, the app is crashing and displays this error message:

<img src="https://user-images.githubusercontent.com/51952998/118495423-78998f00-b723-11eb-98b7-2027a0ce853a.jpeg" width="400" />

When we remove the lib, everything works fine.
We already tried to delete and reinstall node_modules, reinstall Pods, it's not working.

Below, the code that generates the error:

```ts
 if (DeviceInfo.hasNotch()) {
    // in case the notch returns undefined I put
    // a default value that I calculated on an iphone 12
    statusBar = StatusBar.currentHeight || 65;
  }
```

## Expected behavior

We should be able to know if the current device has, or not, a notch.
The function returns a boolean.

**Comment by mikehardy** [comment] 2021-05-17 16:51
Please let me know if you can still reproduce with the example app - without a reproduction I won't be able to help

**Comment by denis0324** [comment] 2021-08-09 18:00
I am getting same issue.

react-native: 0.64.2
react-native-device-info: 8.1.7

**Comment by mikehardy** [comment] 2021-08-09 19:07
@denis0324 and I'm posting the same comment :shrug: 

> Please let me know if you can still reproduce with the example app - without a reproduction I won't be able to help

**Comment by denis0324** [comment] 2021-08-15 03:40
I think this issue is related with react-native-navigation (v 7.18.1)

**Comment by mikehardy** [comment] 2021-08-15 21:18
Without a reproduction there isn't much we can act on anyway unfortunately. I'll close this but discussion may always continue

**Closed by mikehardy** 2021-08-15 21:18 UTC

**Comment by sandergo90** [comment] 2021-09-01 07:29
I've had the same problem in a new react native project. Best advise I can give is to check if any variable that's declared in your Info.plist, is also declared in your project.pbxproj file. For me for example, the string ${MARKETING_VERSION} dit not exist in my project.pbxproj file because I deleted the short version string of my app in Xcode. So when leaving the version empty, react-native-device-info will crash because it tries to fetch a null value.

![image](https://user-images.githubusercontent.com/1516413/131630366-b37ae351-3b4f-4b71-8443-d1c24a807f49.png)

**Comment by mikehardy** [comment] 2021-09-01 13:54
@sandergo90 

> Without a reproduction there isn't much we can act on anyway unfortunately. I'll close this but discussion may always continue

That sounds like you might have a reproduction - if you can post the text of a stack trace from the crash we could find where it was doing unsafe things and perhaps make it null-safe in whatever spot that is - it should not crash of course

**Comment by stevem21m** [comment] 2022-08-24 22:57
Like @sandergo90 said, my project did not have a version number. Once I added a version number (Target > General > Identity > Version) it worked. Thanks

**Comment by mikehardy** [comment] 2022-08-24 23:04
@stevem21m did you get a stack trace from the crash at all? We could guard against it at least
