### ISSUE TITLE
Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.

### ISSUE THREAD

**Issue by bitsaspidy** [react-native-device-info/react-native-device-info#1306] opened 2021-09-14 16:17 UTC
Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

I am getting this issue after install react-native-device-info.

## Summary

|             |     |
| ----------- | --- |
| Version     | 8.3.1   |
| Affected OS | Windows   |

**Comment by mikehardy** [comment] 2021-09-15 15:27
Duplicate of so many issues in the repository, please search first
You have failed to integrate the module properly.

**Closed by mikehardy** 2021-09-15 15:27 UTC
