### ISSUE TITLE
Android build release apk crash

### ISSUE THREAD

**Issue by iOSQiao** [react-native-device-info/react-native-device-info#1144] opened 2020-12-23 01:31 UTC
"react": "16.13.1",
"react-native": "0.63.0",
"react-native-device-info": "^7.3.1",

build release apk.

install and run, it's crashing.

12-23 09:27:38.221 1874-1874/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.awesome, PID: 1874
    java.lang.InternalError: Invoking connectErrno with bad arg 0, type 'Ljava/lang/String;' not instance of 'Ljava/io/FileDescriptor;'
        at com.learnium.RNDeviceInfo.RNDeviceModule.sendEvent(RNDeviceModule.java:953)
        at com.learnium.RNDeviceInfo.RNDeviceModule.access$700(RNDeviceModule.java:70)
        at com.learnium.RNDeviceInfo.RNDeviceModule$1.onReceive(RNDeviceModule.java:117)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
12-23 09:27:38.221 423-909/? W/ActivityManager:   Force finishing activity com.awesome/.MainActivity

**Comment by mikehardy** [comment] 2020-12-23 14:11
Dupe of others https://github.com/react-native-device-info/react-native-device-info/issues?q=is%3Aissue+sendEvent+is%3Aclosed

Clean project and rebuild most likely.

If you can reproduce using the example we can reopen

**Closed by mikehardy** 2020-12-23 14:11 UTC
