### ISSUE TITLE
PRIVACY MANIFEST FILE FOR IOS 

### ISSUE THREAD

**Issue by Vivek-rudhva** [react-native-device-info/react-native-device-info#1622] opened 2024-03-14 09:29 UTC

**Comment by CaptainJeff** [comment] 2024-03-15 15:14
Here are two helpful links describing the issue. It does appear as the root cause is this library

https://stackoverflow.com/questions/78163859/itms-91053-missing-api-declaration-privacy
https://github.com/FlutterFlow/flutterflow-issues/issues/2527

**Comment by LFMAKER** [comment] 2024-03-15 20:39
This library uses NSFileSystemFreeSize, and systemFreeSize needs to declare NSPrivacyAccessedAPICategoryDiskSpace.

**Comment by bqrichards** [comment] 2024-03-15 20:53
Here's an additional resource from Apple about these Privacy Manifest requirements from SDKs and apps:
https://developer.apple.com/videos/play/wwdc2023/10060

**Comment by LFMAKER** [comment] 2024-03-15 21:02
@mikehardy Could you help us with this, do you know if we already have something in mind?

**Comment by frankA10019** [comment] 2024-03-16 17:35
Should I fix this immediately? Or this is just warning and I can fix this before 2024/5/1 ?

**Comment by johnhatvani** [comment] 2024-03-18 03:08
@frankA10019 Its a warning currently, personally like most people I'm sure they have a list of these libraries to work through, I for one would like to see things fixed asap so I can see progress being made.

**Comment by remijean** [comment] 2024-03-18 17:23
Same problem

**Comment by dansimau** [comment] 2024-03-19 16:23
Ideally, if we're not using the calls, it would be great to not have them included in the source code, so that no privacy manifest is required.

Perhaps we could take a similar approach to that of react-native-permissions; if you want to get access to a permission API, you have to uncomment that permission in the Podfile. This links the source code in:
https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#ios

**Comment by dansimau** [comment] 2024-03-19 16:24
Apple docs ref, btw:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by brainbicycle** [comment] 2024-03-19 19:48
:wave: reading the docs and looking at how this field is used in this lib, it sounds to me like it might be worth requesting a new reason for the diskspace apis using the link provided there that is similar to those in the other categories: 

```
Declare this reason if your third-party SDK is providing a wrapper function around file timestamp API(s) for the app to use, and you only access the file timestamp APIs when the app calls your wrapper function. 
This reason may only be declared by third-party SDKs. 
This reason may not be declared if your third-party SDK was created primarily to wrap required reason API(s).
Information accessed for this reason, or any derived information, may not be used for your third-party SDK’s own purposes or sent off-device by your third-party SDK.
```

if such a reason existed for the disk space APIs believe this lib would qualify as it is just asking disk space when client apps request it. Unfortunately currently does not, but might be added if requested. 

barring that a version with a way to not include that code would be great.

**Comment by RhyG** [comment] 2024-03-25 08:10
I've opened this PR to add the privacy manifest, let me know if it's all good or the reasons need to be changed https://github.com/react-native-device-info/react-native-device-info/pull/1624

**Comment by samcheng92** [comment] 2024-03-27 03:31
Does anyone know if this is necessary? [Apple doc](https://developer.apple.com/support/third-party-SDK-requirements/) said only the listing SDKs need to include the privacy manifest file.

**Comment by scblason** [comment] 2024-04-03 22:36
I think is clear that this library should include the manifest. 
React Native team has release a comprehensive post about it: https://github.com/react-native-community/discussions-and-proposals/discussions/776.
Any SDK that does use of APIs that are follow under privacy policy, needs to define a privacy manifest. Since this library use NSUserDefaults, NSFileSystemFreeSize and NSFileSystemSize, it will need to publish a privacy manifest.

**Comment by felixspitzer** [comment] 2024-04-05 06:39
Maybe Async Storage's lastest version can help with some inspiration :D 

https://github.com/react-native-async-storage/async-storage/pull/1076

**Comment by mrtawil** [comment] 2024-04-06 14:13
+1

**Comment by stami-fb** [comment] 2024-04-08 09:18
I ended up removing the disk space code as I didin't need it. A patch below for those interested:
```diff
diff --git a/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m b/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m
index 4b4b4dd..ddf8290 100644
--- a/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m
+++ b/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m
@@ -511,12 +511,7 @@ - (double) getTotalMemory {
 
 - (double) getTotalDiskCapacity {
     uint64_t totalSpace = 0;
-    NSDictionary *storage = [self getStorageDictionary];
-
-    if (storage) {
-        NSNumber *fileSystemSizeInBytes = [storage objectForKey: NSFileSystemSize];
-        totalSpace = [fileSystemSizeInBytes unsignedLongLongValue];
-    }
+    // Remove disk space APIs to not to trigger NSPrivacyAccessedAPICategoryDiskSpace for privacy manifest
     return (double) totalSpace;
 }
 
@@ -530,12 +525,7 @@ - (double) getTotalDiskCapacity {
 
 - (double) getFreeDiskStorage {
     uint64_t freeSpace = 0;
-    NSDictionary *storage = [self getStorageDictionary];
-
-    if (storage) {
-        NSNumber *freeFileSystemSizeInBytes = [storage objectForKey: NSFileSystemFreeSize];
-        freeSpace = [freeFileSystemSizeInBytes unsignedLongLongValue];
-    }
+    // Remove disk space APIs to not to trigger NSPrivacyAccessedAPICategoryDiskSpace for privacy manifest
     return (double) freeSpace;
 }
 

```

**Comment by Nonoyamalfoy** [comment] 2024-04-11 09:39
Thank you for your cooperation.
Also, it looks like this PR is Approved, but will it be merged?https://github.com/react-native-device-info/react-native-device-info/pull/1624
I'm wondering if the privacy manifest will be added as well as AsyncStorage.

**Closed** 2024-04-21 14:53 UTC

**Comment by aryo** [comment] 2024-04-23 05:28
I'm not sure if the reason given for `NSPrivacyAccessedAPICategoryDiskSpace` in https://github.com/react-native-device-info/react-native-device-info/commit/23f95dbe55f38f11fc2cba8efe0eb3e11676d07b is legit.. 

`85F4.1` corresponds to 
> Declare this reason to display disk space information to the person using the device. Disk space may be displayed in units of information (such as bytes) or units of time combined with a media type (such as minutes of HD video).

If we're not using `getTotalDiskCapacity` or  `getFreeDiskStorage`, then we're not displaying disk space info anywhere, meaning if Apple enforces this in the future our apps may be at risk. On top of that, shipping an app with 10.13.2 would arguably break compliance for us.

I think what @dansimau said in https://github.com/react-native-device-info/react-native-device-info/issues/1622#issuecomment-2007619898 would be safer (other than straight up removing the APIs)

> Ideally, if we're not using the calls, it would be great to not have them included in the source code, so that no privacy manifest is required.
> 
> Perhaps we could take a similar approach to that of react-native-permissions; if you want to get access to a permission API, you have to uncomment that permission in the Podfile. This links the source code in: https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#ios
